# fly.toml app configuration file generated for zero2prod-billowing-bird-4500 on 2024-08-11T16:54:28+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zero2prod-billowing-bird-4500'
primary_region = 'ams'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "zero2prod_data"
  destination = "/app/data"
  initial_size = "1gb"

[[vm]]
  size = 'shared-cpu-1x'
