application: 
  port: 8000
database:
  database_name: "sqlite"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-super-secret-token"
  timeout_milliseconds: 10000