# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    environment: production
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run : |
          flyctl secrets set APP_EMAIL_CLIENT__AUTHORIZATION_TOKEN=${{ secrets.POSTMARK_SERVER_API_TOKEN }}
          flyctl secrets set APP_EMAIL_CLIENT__SENDER_EMAIL=${{ secrets.POSTMARK_SENDER_EMAIL }}
          flyctl secrets set APP_APPLICATION__HMAC_SECRET=${{ secrets.HMAC_SECRET }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
